# Generated by Django 4.1.3 on 2023-02-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comments_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ratting',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B')], default=1),
            preserve_default=False,
        ),
    ]
